# This file is a template, and might need editing before it works on your project.

image: node:latest

cache:
  paths:
    - node_modules/
    - app/bower_components

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - yarn
    - yarn run build
    - npm install -g firebase-tools
    - firebase --token $FIREBASE_TOKEN
    - firebase deploy