export const LIST_LOAD_REQUEST = "LIST_LOAD_REQUEST";
export const LIST_LOAD_SUCCESS = "LIST_LOAD_SUCCESS";
export const LIST_LOAD_FAILURE = "LIST_LOAD_FAILURE";

export const ADD_ADDRESS_REQUEST = "ADD_ADDRESS_REQUEST";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const ADD_ADDRESS_FAILURE = "ADD_ADDRESS_FAILURE";
